version: '3'

services:
  stream-data:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /mnt/hdd-2:/data
    command: proxychains4 python scripts/stream-orderbook.py --output-dir /data/stream_orderbook/collected/